import gradio as gr
from pathlib import Path
import subprocess
import shutil

# -----------------------------
# Input/output folders
# -----------------------------
INPUT_DIR = Path("data/input")
OUTPUT_DIR = Path("data/output")
INPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Path to your checkpoint
ICNN_PATH = "checkpoints/NEVERnet/errnet_060_00463920.pt"

def run_errnet(input_image):
    # Clear previous input and output files
    for f in INPUT_DIR.glob("*"):
        f.unlink()
    for f in OUTPUT_DIR.glob("*"):
        if f.is_file():
            f.unlink()
        elif f.is_dir():
            shutil.rmtree(f)

    # Save uploaded image
    img_path = INPUT_DIR / "input.png"
    input_image.save(img_path)

    # Run test_errnet.py
    cmd = [
        "python", "test_nevernet.py",
        "--name", "errnet",
        "-r",
        "--icnn_path", ICNN_PATH,
        "--hyper"
    ]
    subprocess.run(cmd, check=True)

    # Return first image found in output folder
    output_items = list(OUTPUT_DIR.glob("*"))
    if not output_items:
        return None

    first_item = output_items[0]

    # Handle subfolders
    if first_item.is_dir():
        images = list(first_item.glob("*"))
        if images:
            return str(images[0])
    else:
        return str(first_item)

# -----------------------------
# Gradio interface
# -----------------------------
ui = gr.Interface(
    fn=run_errnet,
    inputs=gr.Image(type="pil"),
    outputs=gr.Image(type="filepath"),
    title="NEVERnet Interactive UI",
    description="Upload an image and see the output generated by NEVERnet."
)

ui.launch()
